---
title: ""
output: html_document
---

```{r, echo=FALSE, include=FALSE}
library(tidyverse)
library(tuneR)
library(janitor)
library(kableExtra)
library("formattable")
library(tuneR)
library(dplyr)
library(scales)
```



```{r, echo=FALSE, include=FALSE}
feelix_data <- read.csv("data/feelix/data.csv")
#extraer datos de hapin plus
source("scripts/0_get_hapin_plus.R")
# Emory HAPIN II  
source(file = "scripts/0_get_hapinII.R", encoding = "UTF-8")
```

~~~~
From February 23rd to May 10th 2024
~~~~

```{r, include=FALSE, echo=FALSE}

feelix_data <- feelix_data %>% clean_names() %>% 
  select(index, name, serial_number, time_received, session_id, s3wavefile_url, s3metafile_url) 

# Separate HHID and date

feelix_data_especial<-feelix_data %>% mutate(
  largo_name=str_length(name)
) %>% filter(largo_name=="21")
  
feelix_data_especial$record_id <- substr(feelix_data_especial$name, 7, 11)
feelix_data_especial$date <- as.Date(substr(feelix_data_especial$s3wavefile_url, 6, 15), format = "%m-%d-%Y") 
feelix_data$record_id <- substr(feelix_data$name, 1, 5)
feelix_data$date <- as.Date(substr(feelix_data$s3wavefile_url, 6, 15), format = "%m-%d-%Y")  #"%Y%m%d")
feelix_data<-feelix_data %>% bind_rows(
  feelix_data_especial
)

```

```{r, echo=FALSE, include=FALSE}
# Extract measures
feelix_data <- feelix_data %>% 
  mutate(measure = gsub(".*_(M[0-9]+)\\.wav", "\\1", s3wavefile_url),
                        session = gsub("S([0-9]+)_.*", "S\\1", session_id),
                        serial_number = substr(s3wavefile_url,1,4)) 

feelix_data <- feelix_data %>% 
  select(index, record_id, date, serial_number, session, measure, s3wavefile_url, s3metafile_url)

redcap <- dt_hapin_plus %>% 
  select(id, visit, r1_visit_date, r1_sounds_do, r1_feelix_id, r1_feelix_pos1, r1_feelix_id_m_pos1,feelix_id_s_pos1,
         r1_feelix_pos2, r1_feelix_id_m_pos2, r1_feelix_id_s_pos2, 
         r1_feelix_pos3, r1_feelix_id_s_pos3, r1_feelix_id_m_pos3,
         r1_feelix_pos4, r1_feelix_id_s_pos4, r1_feelix_id_m_pos4)

```


```{r, echo=FALSE, include=FALSE}
#leer lista de archivos de audio completos (WAV y smf)
# Ruta al directorio que contiene los archivos de audio
ruta_directorio <- "data/feelix/recordings"

# Obtener la lista de archivos en el directorio
archivos_audio <- list.files(path = ruta_directorio, full.names = FALSE)

# Crear un data frame con la lista de archivos
recordings_list <- data.frame(archivo_audio = archivos_audio)

```

```{r, echo=FALSE, include=FALSE}
read_and_extract <- function(file_path) {
  # Read audio file
  audio <- readWave(file_path)
  
  # Extract relevant information
  duration <- length(audio) / audio@samp.rate  # Duration in seconds
  # Add more extraction logic as needed
  
  # Return extracted information as a list
  return(list(filename = basename(file_path),
              duration = duration))
}

# Directory containing audio files
audio_dir <- "data/feelix/recordings"

# List audio files in the directory
audio_files <- list.files(audio_dir, pattern = "\\.wav$", full.names = TRUE)

# Read and extract information from audio files
audio_wav <- lapply(audio_files, read_and_extract)

# Convert list to a data frame
wav <- bind_rows(audio_wav)

```


```{r, echo=FALSE, include=FALSE}
#reclutados 5 años
reclutados<-gt_hapin_II_data %>% filter(visit=="b8") %>% filter(s4_consent_c=="1") %>% select(id, s4_date, s4_consent_c)

#examen fisico realizado
redcap_5y<-redcap %>% filter(visit=="5") %>% filter(!is.na(r1_visit_date))
redcap_5y_medidas<-redcap_5y %>% transmute(id, serial_number=r1_feelix_id,
       sesion1=paste0("S",feelix_id_s_pos1), 
       medida1=paste0("M",r1_feelix_id_m_pos1), 
       sesion2=paste0("S",r1_feelix_id_s_pos2),
       medida2=paste0("M",r1_feelix_id_m_pos2),
       sesion3=paste0("S",r1_feelix_id_s_pos3),
       medida3=paste0("M",r1_feelix_id_m_pos3),
       sesion4=paste0("S",r1_feelix_id_s_pos4),
       medida4=paste0("M",r1_feelix_id_m_pos4)
)

redcap_5y_medidas<-redcap_5y_medidas %>% select(
  id, serial_number, sesion=sesion1, medida=medida1
) %>% bind_rows(
  redcap_5y_medidas %>% select(
  id, serial_number, sesion=sesion2, medida=medida2
)
)%>% bind_rows(
  redcap_5y_medidas %>% select(
  id, serial_number, sesion=sesion3, medida=medida3
)
)%>% bind_rows(
  redcap_5y_medidas %>% select(
  id,serial_number,  sesion=sesion4, medida=medida4
)
) 

#integrar comentarios de R1
redcap_5y_medidas<-redcap_5y_medidas %>% left_join(
  dt_hapin_plus %>% filter(redcap_event_name=="5_arm_1") %>% transmute(id,visit=recode(
    r1_visit_do,"1"="Yes",
    "0"="No"
  ),
  recording_sound_rc=recode(r1_sounds_do, "1"="Yes", "0"="No"),
  comments=r1_notes_general)
) 

redcap_5y_medidas_feelix<-redcap_5y_medidas %>% left_join(
  feelix_data %>% select(id=record_id, serial_number, sesion=session, medida=measure,s3wavefile_url )
) 
# %>% filter(is.na(s3wavefile_url)) %>% arrange(id) %>% writexl::write_xlsx("output/revision_redcap_audios_feelix_08052024.xlsx")
#feelix_data %>% writexl::write_xlsx("output/datos_feelix.xlsx")

redcap_5y_medidas_feelix_duration<-redcap_5y_medidas_feelix %>% left_join(
  wav %>% select(s3wavefile_url=filename, duration)
) 

# redcap_5y_medidas_feelix_duration %>% filter(is.na(duration)) %>% filter(is.na(comments)) %>% writexl::write_xlsx(
#   "output/revision_comentarios_feelix.xlsx"
# )



```



```{r, echo=FALSE}
descripcion<-c("Recruited","Physical exam done", "Participants with successful recordings *")
tabla1<-data.frame(descripcion)
tabla1 %>% mutate(
  cantidad=case_when(
    descripcion=="Recruited" ~  reclutados %>% count() %>% .$n,
    descripcion=="Physical exam done" ~ redcap_5y %>% filter(!is.na(r1_visit_date)) %>% count() %>% .$n,
    descripcion=="Participants with successful recordings *" ~  redcap_5y_medidas_feelix_duration %>% filter(!is.na(s3wavefile_url)) %>% filter(duration>10) %>% filter(is.na(comments)) %>%   arrange(id) %>% group_by(id) %>%  mutate(
   numero_grabaciones=row_number() ) %>% ungroup() %>% filter(numero_grabaciones==4) %>% distinct(id) %>% count() %>% .$n
  ),
  proporcion=case_when(
     descripcion=="Recruited" ~  percent(as.numeric(cantidad)/as.numeric(cantidad),1),
     descripcion=="Physical exam done" ~ percent(as.numeric(cantidad) / as.numeric(lag(cantidad)), 1),
      descripcion=="Participants with successful recordings *" ~  percent(as.numeric(cantidad) / as.numeric(lag(cantidad)),1)
  )
  ) %>% transmute(
    " "=descripcion, n=paste0(cantidad," ( ",proporcion, " )")
  ) %>%  kable(caption = "Feelix data completeness report") %>% kable_classic(full_width=F, html_font="Cambria") %>%  
  footnote(general = "* Participant with 4 recordings, downloaded and assigned to their correct Feelix ID")

```



```{r, echo=FALSE, results='asis'}
ids_con_comentarios<-redcap_5y_medidas_feelix_duration %>% filter(!is.na(comments)) %>%  group_by(id,comments) %>% count() %>% ungroup()

#identificar los que no tienen duración mayor a 10 segundos
ids_con_comentarios_duration<-redcap_5y_medidas_feelix_duration %>% filter(duration<11) %>% group_by(id) %>%  count() %>% ungroup() %>% mutate(
  comments="RECORDING WITHOUT DURATION"
)

#unificar comentarios con los que no tienen duración mayor a 10 segundos
ids_con_comentarios<-ids_con_comentarios %>% bind_rows(
  ids_con_comentarios_duration
)

#clasificar las categorias con base en comentarios
ids_con_comentarios_clasificados<-ids_con_comentarios %>% mutate(
  comments=toupper(comments),
  forgotten=if_else(grepl("FORGOT",comments), 1, NA_integer_),
  incorrect_entry=if_else(grepl("INCORRECT ENTRY", comments),1,NA_integer_),
   assigned_another_id=if_else(grepl("ASSIGNED TO ANOTHER", comments),1,NA_integer_),
  missconfigurated=if_else(grepl("MISCONFIGURATED", comments),1,NA_integer_),
  single_session_two_ids=if_else(grepl("SINGLE SESSION", comments),1,NA_integer_),
  lost_session=if_else(grepl("LOST", comments),1,NA_integer_),
  child_not_in_house=if_else(grepl("NOT IN THE HOUSE", comments),1,NA_integer_),
   child_not_cooperate=if_else(grepl("NOT COOPERATE", comments),1,NA_integer_),
  without_duration=if_else(grepl("WITHOUT DURATION", comments),1,NA_integer_),
  
) 

#sacar la cantidad de participantes que no tienen una grabación utilizable
participants_without_succesful_recordings<- ids_con_comentarios_clasificados %>% ungroup() %>% group_by(id) %>% count() %>% ungroup()

long_df <- ids_con_comentarios_clasificados %>%
  pivot_longer(cols = c(forgotten, incorrect_entry, assigned_another_id, missconfigurated, single_session_two_ids, lost_session, child_not_in_house, child_not_cooperate, without_duration),
               names_to = "category",
               values_to = "count") %>%
  filter(!is.na(count))

summary_df <- long_df %>%
  group_by(category) %>%
  summarize(total = sum(count, na.rm = TRUE)) %>%
  arrange(desc(total))


#armar la tabla 2
descripcion<-c(" ")
tabla2<-data.frame(descripcion)
tabla2 %>% mutate(
 participants=participants_without_succesful_recordings %>% count() %>% .$n,
 lost_session=  summary_df %>% filter(category == "lost_session") %>% pull(total) %>% sum(),
 duration= summary_df %>% filter(category == "without_duration") %>% pull(total) %>% sum(),
 misconfigured=summary_df %>% filter(category == "missconfigurated") %>% pull(total) %>% sum(),
 single_session=summary_df %>% filter(category == "single_session_two_ids") %>% pull(total) %>% sum(),
 incorrect_entry=summary_df %>% filter(category == "incorrect_entry") %>% pull(total) %>% sum(),
 another_id=summary_df %>% filter(category == "assigned_another_id") %>% pull(total) %>% sum(),
 child_not_cooperate=summary_df %>% filter(category == "child_not_cooperate") %>% pull(total) %>% sum(),
 child_not_inhouse=summary_df %>% filter(category == "child_not_in_house") %>% pull(total) %>% sum(),
 forgotten=summary_df %>% filter(category == "forgotten") %>% pull(total) %>% sum(),
 prop_lost_session = percent(as.numeric(lost_session) / as.numeric(participants), 1),
    prop_duration = percent(as.numeric(duration) / as.numeric(participants), 1),
    prop_misconfigured = percent(as.numeric(misconfigured) / as.numeric(participants),1),
    prop_single_session = percent(as.numeric(single_session) / as.numeric(participants),1),
    prop_incorrect_entry = percent(as.numeric(incorrect_entry) / as.numeric(participants),1),
    prop_another_id = percent(as.numeric(another_id) / as.numeric(participants),1),
    prop_child_not_cooperate = percent(as.numeric(child_not_cooperate) / as.numeric(participants),1),
    prop_child_not_inhouse = percent(as.numeric(child_not_inhouse) / as.numeric(participants),1),
    prop_forgotten = percent(as.numeric(forgotten) / as.numeric(participants),1)
 
) %>%  transmute(
  "Participants<br>without<br>successful<br>recordings" = paste0(participants, " (100%)"),
    "Participants<br>with lost<br>Session" = paste0(lost_session, " (", prop_lost_session,")"),
    "Participants with<br>audio recordings<br>less than 10<br>seconds" = paste0(duration, " (",prop_duration,")"),
    "Participants with<br>misconfigured<br>recording date" = paste0(misconfigured, " (", prop_misconfigured,")"),
    "Single session<br>with measurements<br>of two<br>participants" = paste0(single_session," (",prop_single_session,")"),
    "Participants with<br>incorrect entry<br>of ID Feelix<br>registration" = paste0(incorrect_entry," (",prop_incorrect_entry,")"),
    "Participants with<br>a session<br>assigned to<br>another ID feelix" = paste0(another_id," (", prop_another_id,")"),
    "Participants<br>didn't<br>cooperate" = paste0(child_not_cooperate," (",prop_child_not_cooperate,")"),
    "Participants<br>weren't available<br>in the house" = paste0(child_not_inhouse," (",prop_child_not_inhouse,")"),
    "Participants<br>not recorded due<br>to unavailable<br>device" = paste0(forgotten," (",prop_forgotten,")")
  ) %>% 
  kable(escape = F, caption = "Reason of participants without successful recordings",
        format = "html") %>% 
  kable_styling(full_width = F, html_font = "Cambria") %>%
  column_spec(1, width = "3cm") %>%  # Ajusta el ancho de la primera columna
  column_spec(2:9, width = "3cm") %>%  # Ajusta el ancho de las demás columnas
  row_spec(0, bold = FALSE, font_size = 10) %>% 
  row_spec(1, bold = FALSE, font_size = 10) 


```


```{r, echo=FALSE, results='asis'}
#armar la tabla 3
Devices<-c("P220","P406","P443")
tabla3<-data.frame(Devices)
tabla3 %>% mutate(
total_issues=case_when(
  Devices=="P220" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P220") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>% select(id) %>% distinct() %>% count() %>% .$n,
  Devices=="P406" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P406") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>% select(id) %>% distinct() %>% count() %>% .$n,
  Devices=="P443" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P443") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>%select(id) %>% distinct() %>% count() %>% .$n
),
lost_session=case_when(
  Devices=="P220" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P220") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>% filter(grepl("LOST", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n,
  Devices=="P406" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P406") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>%  filter(grepl("LOST", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n,
  Devices=="P443" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P443") %>%   filter(is.na(s3wavefile_url) | !is.na(comments))  %>% filter(grepl("LOST", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n
),
misconfigured=case_when(
  Devices=="P220" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P220") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>% filter(grepl("MISCONFIGURATED", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n,
  Devices=="P406" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P406") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>%  filter(grepl("MISCONFIGURATED", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n,
  Devices=="P443" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P443") %>%   filter(is.na(s3wavefile_url) | !is.na(comments))  %>% filter(grepl("MISCONFIGURATED", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n
),
single_session=case_when(
  Devices=="P220" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P220") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>% filter(grepl("SINGLE SESSION", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n,
  Devices=="P406" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P406") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>%  filter(grepl("SINGLE SESSION", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n,
  Devices=="P443" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P443") %>%   filter(is.na(s3wavefile_url) | !is.na(comments))  %>% filter(grepl("SINGLE SESSION", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n
),
incorrect_id=case_when(
  Devices=="P220" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P220") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>% filter(grepl("INCORRECT ENTRY", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n,
  Devices=="P406" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P406") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>%  filter(grepl("INCORRECT ENTRY", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n,
  Devices=="P443" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P443") %>%   filter(is.na(s3wavefile_url) | !is.na(comments))  %>% filter(grepl("INCORRECT ENTRY", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n
),
assigned_another=case_when(
  Devices=="P220" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P220") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>% filter(grepl("ASSIGNED TO ANOTHER", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n,
  Devices=="P406" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P406") %>%   filter(is.na(s3wavefile_url) | !is.na(comments)) %>%  filter(grepl("ASSIGNED TO ANOTHER", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n,
  Devices=="P443" ~ redcap_5y_medidas_feelix %>%filter(serial_number=="P443") %>%   filter(is.na(s3wavefile_url) | !is.na(comments))  %>% filter(grepl("ASSIGNED TO ANOTHER", comments)) %>% select(id) %>% distinct() %>% count() %>% .$n
),
p_lost_session=percent(as.numeric(lost_session)/as.numeric(total_issues),1),
p_misconfigured=percent(as.numeric(misconfigured)/as.numeric(total_issues),1),
p_single_session=percent(as.numeric(single_session)/as.numeric(total_issues),1),
p_incorrect_id=percent(as.numeric(incorrect_id)/as.numeric(total_issues),1),
p_assigned_another=percent(as.numeric(assigned_another)/as.numeric(total_issues),1)
  ) %>% transmute(
    Devices,
    "Total issues"=paste0(total_issues, " (100%)"),
    "Participants<br>with lost<br>Session" = paste0(lost_session, " (", p_lost_session,")"),
    "Participants with<br>misconfigured<br>recording date" = paste0(misconfigured, " (", p_misconfigured,")"),
    "Single session<br>with measurements<br>of two<br>participants" = paste0(single_session," (",p_single_session,")"),
     "Participants with<br>incorrect entry<br>of ID Feelix<br>registration" = paste0(incorrect_id," (",p_incorrect_id,")"),
    "Participants with<br>a session<br>assigned to<br>another ID feelix" = paste0(assigned_another," (", p_assigned_another,")"),
  ) %>% 
  kable(escape = F, caption = "Issues related with Feelix downloading process",
        format = "html")%>% 
  kable_styling(full_width = F, html_font = "Cambria") %>%
  column_spec(1, width = "3cm" ) %>%  # Ajusta el ancho de la primera columna
  column_spec(2:7, width = "3cm") %>%  # Ajusta el ancho de las demás columnas
  row_spec(0, bold = FALSE, font_size = 10) %>% 
  row_spec(1:3, bold = FALSE, font_size = 10) %>% 
   footnote(general = "During the week of April 8th, the device P406 was suspended from use in the field due to issues with slow downloading and processing.")


#During the week of April 8th, the device P406 was suspended from use in the field due to issues with slow downloading and processing.
```


```{r, echo=FALSE, include=FALSE}

 # Obtener una lista de todos los archivos .wav en la carpeta
 #file_list <- list.files(path = "data/feelix/recordings", pattern = "\\.wav$")
 file_list<- wav %>% filter(duration>10) %>%  transmute(file=paste0("data/feelix/recordings/",filename))

 analyze_audio <- function(file_path, sensitivity_factor) {
   wav_file <- readWave(file_path)

   if (wav_file@stereo) {
     signal <- (wav_file@left + wav_file@right) / 2
   } else {
     signal <- wav_file@left
   }

   fft_result <- fft(signal)
   magnitudes <- Mod(fft_result)
   half_index <- length(magnitudes) / 2
   frequencies <- seq(0, wav_file@samp.rate / 2, length.out = half_index)

   # Definir umbrales considerando el rango pediátrico
   high_freq_threshold = 2000  # Considerar una frecuencia de corte más alta
   high_magnitude_threshold = median(magnitudes) * sensitivity_factor  # Ajustar según las necesidades de sensibilidad

   # Identificar si hay frecuencias altas con magnitudes altas
   high_freqs = which(frequencies >= high_freq_threshold & magnitudes[1:half_index] >= high_magnitude_threshold)

   if (length(high_freqs) > 0) {
     return(TRUE)
   } else {
     return(FALSE)
   }
 }

 results <- sapply(file_list$file, analyze_audio, sensitivity_factor = 15)
 anomalous_files <- file_list$file[results]
 print(anomalous_files)




 # Mostrar los nombres de los archivos con posibles condiciones respiratorias anormales
 anomalous_files <- file_list$file[results]
 print(anomalous_files)



```



```{r, echo=FALSE, include=FALSE}

 wav_file<-readWave("data/feelix/recordings/P406_02-14-2024-01-58-16-S7_M4.wav")

 # Asumiendo que wav_file ya está cargado y es mono. Si es estéreo, convierte a mono:
 if (wav_file@stereo) {
   signal <- (wav_file@left + wav_file@right) / 2
 } else {
   signal <- wav_file@left
 }

 # Realizar la FFT
 fft_result <- fft(signal)

 # Calcular magnitudes (amplitudes)
 magnitudes <- Mod(fft_result)

 # La longitud de la muestra de FFT dividida por 2 (solo frecuencias positivas son necesarias)
 half_length <- length(magnitudes) / 2

 # Calcular las frecuencias (solo positivas)
 frequencies <- seq(0, wav_file@samp.rate/2, length.out = half_length)

 # # Plotear las frecuencias contra las magnitudes
 # plot(frequencies, magnitudes[1:half_length], type = 'l', xlab = "Frequency (Hz)", ylab = "Magnitude", main = "Frequency Spectrum")


 # Definir el rango de eje Y basado en los datos
 max_magnitude <- max(magnitudes[1:half_length])
 y_at <- seq(0, max_magnitude, length.out = 5)

 # Usar magnitudes originales sin escalar para el eje Y
 plot(frequencies, magnitudes[1:half_length], type = 'l',
    xlab = "Frequency (Hz)", ylab = "Magnitude",
      ylim = c(0, max_magnitude),
      main = "Frequency Spectrum",
      yaxt = 'n') + # Suprimir el eje Y automático

 # Formatear eje Y para evitar notación científica, asegurándose de que es parte del mismo bloque
 axis(2, at = y_at, labels = format(y_at, scientific = FALSE))


```
 
 
```{r}


 # Nombres de los archivos
 files <- c("P406_02-14-2024-01-58-16-S7_M1.wav", "P406_02-14-2024-01-58-00-S7_M1.wav", "P406_02-14-2024-01-58-16-S7_M3.wav", "P406_02-14-2024-01-58-16-S7_M4.wav")

 # Lista para almacenar los datos de audio
 audio_data <- list()

 # Cargar los archivos y almacenarlos en la lista
 for (i in 1:length(files)) {
     # Asume que los archivos están en el directorio "data/feelix/recordings/"
     audio_data[[i]] <- readWave(paste0("data/feelix/recordings/", files[i]))
 }


 for (i in 1:length(audio_data)) {
     wav_file <- audio_data[[i]]

     # Convertir a mono si es estéreo
     if (wav_file@stereo) {
         signal <- (wav_file@left + wav_file@right) / 2
     } else {
         signal <- wav_file@left
     }

     # Realizar la FFT
     fft_result <- fft(signal)
     magnitudes <- Mod(fft_result)
     half_length <- length(magnitudes) / 2
     frequencies <- seq(0, wav_file@samp.rate/2, length.out = half_length)

     # Plotear las frecuencias contra las magnitudes
     plot(frequencies, magnitudes[1:half_length], type = 'l',
          xlab = "Frequency (Hz)", ylab = "Magnitude",
          main = paste("Frequency Spectrum of", files[i]),
          ylim = c(0, max(magnitudes[1:half_length])))
 }

 
 #redcap_5y_medidas_feelix_duration %>% filter(s3wavefile_url=="P406_02-14-2024-01-58-16-S7_M4.wav")
```

