#cargar librerias y paquetes
library("tidyverse")
library(readxl)
library(openxlsx)
library(janitor)

# Emory RedCap export data
source(file = "scripts/0_get_emory_data.R", encoding = "UTF-8")

# Emory HAPIN II  
source(file = "scripts/0_get_hapinII.R", encoding = "UTF-8")

#calcular la edad para los niños que hicieron mdat 36m ----
edad_36m<-gt_hapin_II_data %>% filter(!is.na(c85_date))  %>% select(id, fecha_c85=c85_date) %>% 
  left_join(
    gt_emory_data_arm2 %>% filter(!is.na(c30_dob)) %>% select(id, fec_nac=c30_dob)
  ) %>% mutate(
    age=round((as.Date(fecha_c85) - as.Date(fec_nac))/365,2)
  ) %>% select(original_id=id, decimalage=age)
#test ----
edad_36m %>% left_join(
gt_hapin_II_data %>% filter(!is.na(c85_date)) %>%  filter(visit=="b6") %>%  select(original_id=id,
                                                         GM1=c85_chin,
                                                         GM2=c85_prone,
                                                         GM3=c85_lift_head,
                                                         GM4=c85_headup,
                                                         GM5=c85_pullsit,
                                                         GM6=c85_sit,
                                                         GM7=0,
                                                         GM8=c85_bear_wt,
                                                         GM9=c85_roll,
                                                         GM10=c85_sit_10sec,
                                                         GM11=c85_sit_30sec,
                                                         GM12=c85_crawl,
                                                         GM13=c85_pull_stand,
                                                         GM14=c85_hold_stand,
                                                         GM15=0,
                                                         GM16=c85_walk_2hand,
                                                         GM17=c85_walk_help,
                                                         GM18=c85_walk_fall,
                                                         GM19=c85_stoop,
                                                         GM20=c85_walk_well,
                                                         GM21=0,
                                                         GM22=c85_run,
                                                         GM23=c85_run_well,
                                                         GM24=c85_kick,
                                                         GM25=c85_run_kick,
                                                         GM26=c85_ball_basket,
                                                         GM27=c85_kneel_up,
                                                         GM28=0,
                                                         GM29=c85_jump_off,
                                                         GM30=c85_jump_over,
                                                         GM31=c85_walk_heel,
                                                         GM32=c85_tip_toe,
                                                         GM33=c85_stand_1foot,
                                                         GM34=c85_1foot_5sec,
                                                         GM35=0,
                                                         GM36=c85_jump_a4,
                                                         GM37=c85_hop,
                                                         GM38=0,
                                                         GM39=c85_walk_string,
                                                         GM40=0,
                                                         GM41=c85_catch_ball,
                                                         GM42=0,
                                                         GM43=0,
                                                         GM44=0,
                                                         GM45=0,
                                                         FM1=c85_follow_mom,
                                                         FM2=c85_follow_rl,
                                                         FM3=c85_hands_eye,
                                                         FM4=c85_reach_large,
                                                         FM5=c85_hold_large,
                                                         FM6=c85_object_mouth,
                                                         FM7=c85_look_small,
                                                         FM8=c85_pick_large,
                                                         FM9=c85_transfer,
                                                         FM10=c85_clap,
                                                         FM11=c85_pick_small,
                                                         FM12=c85_hidden,
                                                         FM13=c85_pincer,
                                                         FM14=c85_push_car,
                                                         FM15=0,
                                                         FM16=c85_in_jar,
                                                         FM17=c85_out_jar,
                                                         FM18=c85_straight_line,
                                                         FM19=c85_circular_line,
                                                         FM20=0,
                                                         FM21=0,
                                                         FM22=0,
                                                         FM23=c85_peg_2min,
                                                         FM24=c85_peg_30sec,
                                                         FM25.2=0,
                                                         FM25.4=0,
                                                         FM25.6=0,
                                                         FM26=c85_screw,
                                                         FM27=0,
                                                         FM28=c85_vertical,
                                                         FM29=c85_circle,
                                                         FM30=c85_cross,
                                                         FM31=c85_bridge,
                                                         FM32=c85_thread,
                                                         FM33=0,
                                                         FM34=0,
                                                         FM35=c85_size,
                                                         FM36=c85_weight,
                                                         FM37=c85_fold,
                                                         FM38=c85_square,
                                                         FM39=c85_6bridge,
                                                         FM40=c85_6stair,
                                                         FM41=c85_top_row,
                                                         FM42=c85_top_sq,
                                                         FM43=0,
                                                         FM44=0,
                                                         FM45=0,
                                                         FM46=0,
                                                         FM47=0,
                                                         FM48=0,
                                                         FM49=0,
                                                         FM50=0,
                                                         FM51=0,
                                                         FM52=0,
                                                         FM53=0,
                                                         FM54=0,
                                                         FM55=0,
                                                         FM56=0,
                                                         LA1=c85_startle,
                                                         LA2=c85_happy,
                                                         LA3=c85_laugh,
                                                         LA4=c85_turns,
                                                         LA5=c85_single_syl,
                                                         LA6=c85_two_syl,
                                                         LA7=c85_understand_no,
                                                         LA8=c85_resp_name,
                                                         LA9=c85_indicate_no,
                                                         LA10=c85_1command,
                                                         LA11=c85_pretend_talk,
                                                         LA12.2=c85_words,
                                                         LA12.4=0,
                                                         LA12.6=c85_6words,
                                                         LA12.8=0,
                                                         LA13=c85_words,
                                                         LA14.5=c85_5_identify,
                                                         LA14.10=c85_10_identify,
                                                         LA15=c85_2command,
                                                         LA16=0,
                                                         LA17=0,
                                                         LA18=c85_bodypart,
                                                         LA19=0,
                                                         LA20.5=c85_5_name,
                                                         LA20.10=c85_10_name,
                                                         LA21=0,
                                                         LA22=c85_sentence,
                                                         LA23=c85_actions,
                                                         LA24=c85_own_name,
                                                         LA25=0,
                                                         LA26=c85_position,
                                                         LA27=0,
                                                         LA28=c85_adjec,
                                                         LA29=c85_know_use,
                                                         LA30.2=c85_2repeat_syl,
                                                         LA30.4=c85_4repeat_syl,
                                                         LA31=c85_faster,
                                                         LA32=c85_categorize,
                                                         LA33=c85_3stage,
                                                         LA34=0,
                                                         LA35.3=c85_3count,
                                                         LA35.5=c85_5count,
                                                         LA35.10=c85_10count,
                                                         LA36=0,
                                                         LA37=c85_sing,
                                                         LA38=0,
                                                         LA39=c85_age,
                                                         LA40=c85_oposite,
                                                         LA41=c85_material,
                                                         LA42=c85_explain_past,
                                                         LA43=0,
                                                         LA44=0,
                                                         LA45=0,
                                                         LA46=0,
                                                         LA47=0,
                                                         LA48=0,
                                                         LA49=0,
                                                         LA50=0,
                                                         LA51=0,
                                                         LA52=0,
                                                         LA53=0,
                                                         LA54=0,
                                                         LA55=0,
                                                         LA56=0,
                                                         LA57=0,
                                                         LA58=0,
                                                         SO1=c85_smile,
                                                         SO2=c85_smile_person,
                                                         SO3=c85_playful_with,
                                                         SO4=0,
                                                         SO5=c85_playful,
                                                         SO6=c85_spoon_fed,
                                                         SO7=c85_hold_cup,
                                                         SO8=c85_strech,
                                                         SO9=c85_hold_spoon,
                                                         SO10=c85_point,
                                                         SO11=c85_pick_food,
                                                         SO12=0,
                                                         SO13=c85_cup_drink,
                                                         SO14=c85_hand_up,
                                                         SO15=c85_spoon_no_spil,
                                                         SO16=c85_pick_food,
                                                         SO17=c85_asks_food,
                                                         SO18=c85_potty,
                                                         SO19=c85_greet,
                                                         SO20=c85_join_sing,
                                                         SO21=c85_undress,
                                                         SO22=0,
                                                         SO23=c85_share,
                                                         SO24=c85_spoon_no_spil,
                                                         SO25=c85_eat_bit,
                                                         SO26=c85_chore,
                                                         SO27=c85_wash_hand,
                                                         SO28=c85_toilet,
                                                         SO29=0,
                                                         SO30=c85_dress_part,
                                                         SO31=0,
                                                         SO32=c85_dress,
                                                         SO33=c85_independence,
                                                         SO34=0,
                                                         SO35=0,
                                                         SO36=0,
                                                         SO37=c85_take_turn,
                                                         SO38=c85_respect,
                                                         SO39=c85_discipline,
                                                         SO40=c85_toilet_self,
                                                         SO41=c85_quiet,
                                                         SO42=0,
                                                         SO43=0,
                                                         SO44=0,
                                                         SO45=0,
                                                         SO46=0,
                                                         SO47=0,
                                                         SO48=0,
                                                         SO49=0,
                                                         SO50=0,
                                                         SO51=0,
                                                         SO52=0,
                                                         SO53=0,
                                                         SO54=0,
                                                         SO55=0,
                                                         TQQ1=0,
                                                         TQQ2=0,
                                                         TQQ3=0,
                                                         TQQ4=0,
                                                         TQQ5=0,
                                                         TQQ6=0,
                                                         TQQ7=0,
                                                         TQQ8=0,
                                                         TQQ9=0,
                                                         TQQ10=0,
                                                         poss_dis=0
                                                         
                                                         
   ) %>% mutate_all(., ~replace(., is.na(.) | .=="98", 0))
) %>% writexl::write_xlsx("output/Data template v1.1.cs")


#ajuste a las variables de la plantilla ----
edad_36m %>% left_join(
  gt_hapin_II_data %>% filter(!is.na(c85_date))%>%  transmute(original_id=id,
                                                                                     GM1=c85_chin,
                                                                                     GM2=c85_prone,
                                                                                     GM3=c85_lift_head,
                                                                                     GM4=c85_headup,
                                                                                     GM5=c85_pullsit,
                                                                                     GM6=c85_sit,
                                                                                     GM7=0,
                                                                                     GM8=c85_bear_wt,
                                                                                     GM9=c85_roll,
                                                                                     GM10=c85_sit_10sec,
                                                                                     GM11=c85_sit_30sec,
                                                                                     GM12=c85_crawl,
                                                                                     GM13=c85_pull_stand,
                                                                                     GM14=c85_hold_stand,
                                                                                     GM15=0,
                                                                                     GM16=c85_walk_2hand,
                                                                                     GM17=c85_walk_help,
                                                                                     GM18=c85_walk_fall,
                                                                                     GM19=c85_stoop,
                                                                                     GM20=c85_walk_well,
                                                                                     GM21=0,
                                                                                     GM22=c85_run,
                                                                                     GM23=c85_run_well,
                                                                                     GM24=c85_kick,
                                                                                     GM25=c85_run_kick,
                                                                                     GM26=c85_ball_basket,
                                                                                     GM27=c85_kneel_up,
                                                                                     GM28=0,
                                                                                     GM29=c85_jump_off,
                                                                                     GM30=c85_jump_over,
                                                                                     GM31=c85_walk_heel,
                                                                                     GM32=c85_tip_toe,
                                                                                     GM33=c85_stand_1foot,
                                                                                     GM34=c85_1foot_5sec,
                                                                                     GM35=0,
                                                                                     GM36=c85_jump_a4,
                                                                                     GM37=c85_hop,
                                                                                     GM38=0,
                                                                                     GM39=c85_walk_string,
                                                                                     GM40=0,
                                                                                     GM41=c85_catch_ball,
                                                                                     GM42=0,
                                                                                     GM43=0,
                                                                                     GM44=0,
                                                                                     GM45=0,
                                                                                     FM1=c85_follow_mom,
                                                                                     FM2=c85_follow_rl,
                                                                                     FM3=c85_hands_eye,
                                                                                     FM4=c85_reach_large,
                                                                                     FM5=c85_hold_large,
                                                                                     FM6=c85_object_mouth,
                                                                                     FM7=c85_look_small,
                                                                                     FM8=c85_pick_large,
                                                                                     FM9=c85_transfer,
                                                                                     FM10=c85_clap,
                                                                                     FM11=c85_pick_small,
                                                                                     FM12=c85_hidden,
                                                                                     FM13=c85_pincer,
                                                                                     FM14=c85_push_car,
                                                                                     FM15=0,
                                                                                     FM16=c85_in_jar,
                                                                                     FM17=c85_out_jar,
                                                                                     FM18=c85_straight_line,
                                                                                     FM19=c85_circular_line,
                                                                                     FM20=0,
                                                                                     FM21=0,
                                                                                     FM22=0,
                                                                                     FM23=c85_peg_2min,
                                                                                     FM24=c85_peg_30sec,
                                                                                     FM25.2=0,
                                                                                     FM25.4=0,
                                                                                     FM25.6=0,
                                                                                     FM26=c85_screw,
                                                                                     FM27=0,
                                                                                     FM28=c85_vertical,
                                                                                     FM29=c85_circle,
                                                                                     FM30=c85_cross,
                                                                                     FM31=c85_bridge,
                                                                                     FM32=c85_thread,
                                                                                     FM33=0,
                                                                                     FM34=0,
                                                                                     FM35=c85_size,
                                                                                     FM36=c85_weight,
                                                                                     FM37=c85_fold,
                                                                                     FM38=c85_square,
                                                                                     FM39=c85_6bridge,
                                                                                     FM40=c85_6stair,
                                                                                     FM41=c85_top_row,
                                                                                     FM42=c85_top_sq,
                                                                                     FM43=0,
                                                                                     FM44=0,
                                                                                     FM45=0,
                                                                                     FM46=0,
                                                                                     FM47=0,
                                                                                     FM48=0,
                                                                                     FM49=0,
                                                                                     FM50=0,
                                                                                     FM51=0,
                                                                                     FM52=0,
                                                                                     FM53=0,
                                                                                     FM54=0,
                                                                                     FM55=0,
                                                                                     FM56=0,
                                                                                     LA1=c85_startle,
                                                                                     LA2=c85_happy,
                                                                                     LA3=c85_laugh,
                                                                                     LA4=c85_turns,
                                                                                     LA5=c85_single_syl,
                                                                                     LA6=c85_two_syl,
                                                                                     LA7=c85_understand_no,
                                                                                     LA8=c85_resp_name,
                                                                                     LA9=c85_indicate_no,
                                                                                     LA10=c85_1command,
                                                                                     LA11=c85_pretend_talk,
                                                                                     LA12.2=c85_words,
                                                                                     LA12.4=0,
                                                                                     LA12.6=c85_6words,
                                                                                     LA12.8=0,
                                                                                     LA13=c85_words,
                                                                                     LA14.5=c85_5_identify,
                                                                                     LA14.10=c85_10_identify,
                                                                                     LA15=c85_2command,
                                                                                     LA16=0,
                                                                                     LA17=0,
                                                                                     LA18=c85_bodypart,
                                                                                     LA19=0,
                                                                                     LA20.5=c85_5_name,
                                                                                     LA20.10=c85_10_name,
                                                                                     LA21=0,
                                                                                     LA22=c85_sentence,
                                                                                     LA23=c85_actions,
                                                                                     LA24=c85_own_name,
                                                                                     LA25=0,
                                                                                     LA26=c85_position,
                                                                                     LA27=0,
                                                                                     LA28=c85_adjec,
                                                                                     LA29=c85_know_use,
                                                                                     LA30.2=c85_2repeat_syl,
                                                                                     LA30.4=c85_4repeat_syl,
                                                                                     LA31=c85_faster,
                                                                                     LA32=c85_categorize,
                                                                                     LA33=c85_3stage,
                                                                                     LA34=0,
                                                                                     LA35.3=c85_3count,
                                                                                     LA35.5=c85_5count,
                                                                                     LA35.10=c85_10count,
                                                                                     LA36=0,
                                                                                     LA37=c85_sing,
                                                                                     LA38=0,
                                                                                     LA39=c85_age,
                                                                                     LA40=c85_oposite,
                                                                                     LA41=c85_material,
                                                                                     LA42=c85_explain_past,
                                                                                     LA43=0,
                                                                                     LA44=0,
                                                                                     LA45=0,
                                                                                     LA46=0,
                                                                                     LA47=0,
                                                                                     LA48=0,
                                                                                     LA49=0,
                                                                                     LA50=0,
                                                                                     LA51=0,
                                                                                     LA52=0,
                                                                                     LA53=0,
                                                                                     LA54=0,
                                                                                     LA55=0,
                                                                                     LA56=0,
                                                                                     LA57=0,
                                                                                     LA58=0,
                                                                                     SO1=c85_smile,
                                                                                     SO2=c85_smile_person,
                                                                                     SO3=c85_playful_with,
                                                                                     SO4=0,
                                                                                     SO5=c85_playful,
                                                                                     SO6=c85_spoon_fed,
                                                                                     SO7=c85_hold_cup,
                                                                                     SO8=c85_strech,
                                                                                     SO9=c85_hold_spoon,
                                                                                     SO10=c85_point,
                                                                                     SO11=c85_pick_food,
                                                                                     SO12=0,
                                                                                     SO13=c85_cup_drink,
                                                                                     SO14=c85_hand_up,
                                                                                     SO15=c85_spoon_no_spil,
                                                                                     SO16=c85_pick_food,
                                                                                     SO17=c85_asks_food,
                                                                                     SO18=c85_potty,
                                                                                     SO19=c85_greet,
                                                                                     SO20=c85_join_sing,
                                                                                     SO21=c85_undress,
                                                                                     SO22=0,
                                                                                     SO23=c85_share,
                                                                                     SO24=c85_spoon_no_spil,
                                                                                     SO25=c85_eat_bit,
                                                                                     SO26=c85_chore,
                                                                                     SO27=c85_wash_hand,
                                                                                     SO28=c85_toilet,
                                                                                     SO29=0,
                                                                                     SO30=c85_dress_part,
                                                                                     SO31=0,
                                                                                     SO32=c85_dress,
                                                                                     SO33=c85_independence,
                                                                                     SO34=0,
                                                                                     SO35=0,
                                                                                     SO36=0,
                                                                                     SO37=c85_take_turn,
                                                                                     SO38=c85_respect,
                                                                                     SO39=c85_discipline,
                                                                                     SO40=c85_toilet_self,
                                                                                     SO41=c85_quiet,
                                                                                     SO42=0,
                                                                                     SO43=0,
                                                                                     SO44=0,
                                                                                     SO45=0,
                                                                                     SO46=0,
                                                                                     SO47=0,
                                                                                     SO48=0,
                                                                                     SO49=0,
                                                                                     SO50=0,
                                                                                     SO51=0,
                                                                                     SO52=0,
                                                                                     SO53=0,
                                                                                     SO54=0,
                                                                                     SO55=0
       
                                                                                     
  ) %>% mutate_all(., ~replace(., is.na(.) | .=="98", 0))
) %>% write_csv("output/Data_template0_36m_48m_v1.1.csv")


#calcular la edad para los niños que hicieron mdat 48m ----
#%>% filter(visit=="b7")
edad_48m<-gt_hapin_II_data %>% filter(!is.na(c85_date))  %>% select(id, fecha_c85=c85_date) %>% 
  left_join(
    gt_emory_data_arm2 %>% filter(!is.na(c30_dob)) %>% select(id, fec_nac=c30_dob)
  ) %>% mutate(
    age=round((as.Date(fecha_c85) - as.Date(fec_nac))/365,2)
  ) %>% select(original_id=id, decimalage=age)

#ajuste a las variables de la plantilla ----
#%>%  filter(visit=="b7")
edad_48m %>% left_join(
  gt_hapin_II_data %>% filter(!is.na(c85_date))  %>%  transmute(original_id=id,
                                                                                        GM1=c85_chin,
                                                                                        GM2=c85_prone,
                                                                                        GM3=c85_lift_head,
                                                                                        GM4=c85_headup,
                                                                                        GM5=c85_pullsit,
                                                                                        GM6=c85_sit,
                                                                                        GM7=NA,
                                                                                        GM8=c85_bear_wt,
                                                                                        GM9=c85_roll,
                                                                                        GM10=c85_sit_10sec,
                                                                                        GM11=c85_sit_30sec,
                                                                                        GM12=c85_crawl,
                                                                                        GM13=c85_pull_stand,
                                                                                        GM14=c85_hold_stand,
                                                                                        GM15=NA,
                                                                                        GM16=c85_walk_2hand,
                                                                                        GM17=c85_walk_help,
                                                                                        GM18=c85_walk_fall,
                                                                                        GM19=c85_stoop,
                                                                                        GM20=c85_walk_well,
                                                                                        GM21=NA,
                                                                                        GM22=c85_run,
                                                                                        GM23=c85_run_well,
                                                                                        GM24=c85_kick,
                                                                                        GM25=c85_run_kick,
                                                                                        GM26=c85_ball_basket,
                                                                                        GM27=c85_kneel_up,
                                                                                        GM28=NA,
                                                                                        GM29=c85_jump_off,
                                                                                        GM30=c85_jump_over,
                                                                                        GM31=c85_walk_heel,
                                                                                        GM32=c85_tip_toe,
                                                                                        GM33=c85_stand_1foot,
                                                                                        GM34=c85_1foot_5sec,
                                                                                        GM35=NA,
                                                                                        GM36=c85_jump_a4,
                                                                                        GM37=c85_hop,
                                                                                        GM38=NA,
                                                                                        GM39=c85_walk_string,
                                                                                        GM40=NA,
                                                                                        GM41=c85_catch_ball,
                                                                                        GM42=NA,
                                                                                        GM43=NA,
                                                                                        GM44=NA,
                                                                                        GM45=NA,
                                                                                        FM1=c85_follow_mom,
                                                                                        FM2=c85_follow_rl,
                                                                                        FM3=c85_hands_eye,
                                                                                        FM4=c85_reach_large,
                                                                                        FM5=c85_hold_large,
                                                                                        FM6=c85_object_mouth,
                                                                                        FM7=c85_look_small,
                                                                                        FM8=c85_pick_large,
                                                                                        FM9=c85_transfer,
                                                                                        FM10=c85_clap,
                                                                                        FM11=c85_pick_small,
                                                                                        FM12=c85_hidden,
                                                                                        FM13=c85_pincer,
                                                                                        FM14=c85_push_car,
                                                                                        FM15=NA,
                                                                                        FM16=c85_in_jar,
                                                                                        FM17=c85_out_jar,
                                                                                        FM18=c85_straight_line,
                                                                                        FM19=c85_circular_line,
                                                                                        FM20=NA,
                                                                                        FM21=NA,
                                                                                        FM22=NA,
                                                                                        FM23=c85_peg_2min,
                                                                                        FM24=c85_peg_30sec,
                                                                                        FM25.2=NA,
                                                                                        FM25.4=NA,
                                                                                        FM25.6=NA,
                                                                                        FM26=c85_screw,
                                                                                        FM27=NA,
                                                                                        FM28=c85_vertical,
                                                                                        FM29=c85_circle,
                                                                                        FM30=c85_cross,
                                                                                        FM31=c85_bridge,
                                                                                        FM32=c85_thread,
                                                                                        FM33=NA,
                                                                                        FM34=NA,
                                                                                        FM35=c85_size,
                                                                                        FM36=c85_weight,
                                                                                        FM37=c85_fold,
                                                                                        FM38=c85_square,
                                                                                        FM39=c85_6bridge,
                                                                                        FM40=c85_6stair,
                                                                                        FM41=c85_top_row,
                                                                                        FM42=c85_top_sq,
                                                                                        FM43=NA,
                                                                                        FM44=NA,
                                                                                        FM45=NA,
                                                                                        FM46=NA,
                                                                                        FM47=NA,
                                                                                        FM48=NA,
                                                                                        FM49=NA,
                                                                                        FM50=NA,
                                                                                        FM51=NA,
                                                                                        FM52=NA,
                                                                                        FM53=NA,
                                                                                        FM54=NA,
                                                                                        FM55=NA,
                                                                                        FM56=NA,
                                                                                        LA1=c85_startle,
                                                                                        LA2=c85_happy,
                                                                                        LA3=c85_laugh,
                                                                                        LA4=c85_turns,
                                                                                        LA5=c85_single_syl,
                                                                                        LA6=c85_two_syl,
                                                                                        LA7=c85_understand_no,
                                                                                        LA8=c85_resp_name,
                                                                                        LA9=c85_indicate_no,
                                                                                        LA10=c85_1command,
                                                                                        LA11=c85_pretend_talk,
                                                                                        LA12.2=c85_words,
                                                                                        LA12.4=NA,
                                                                                        LA12.6=c85_6words,
                                                                                        LA12.8=NA,
                                                                                        LA13=c85_words,
                                                                                        LA14.5=c85_5_identify,
                                                                                        LA14.10=c85_10_identify,
                                                                                        LA15=c85_2command,
                                                                                        LA16=NA,
                                                                                        LA17=NA,
                                                                                        LA18=c85_bodypart,
                                                                                        LA19=NA,
                                                                                        LA20.5=c85_5_name,
                                                                                        LA20.10=c85_10_name,
                                                                                        LA21=NA,
                                                                                        LA22=c85_sentence,
                                                                                        LA23=c85_actions,
                                                                                        LA24=c85_own_name,
                                                                                        LA25=NA,
                                                                                        LA26=c85_position,
                                                                                        LA27=NA,
                                                                                        LA28=c85_adjec,
                                                                                        LA29=c85_know_use,
                                                                                        LA30.2=c85_2repeat_syl,
                                                                                        LA30.4=c85_4repeat_syl,
                                                                                        LA31=c85_faster,
                                                                                        LA32=c85_categorize,
                                                                                        LA33=c85_3stage,
                                                                                        LA34=NA,
                                                                                        LA35.3=c85_3count,
                                                                                        LA35.5=c85_5count,
                                                                                        LA35.10=c85_10count,
                                                                                        LA36=NA,
                                                                                        LA37=c85_sing,
                                                                                        LA38=NA,
                                                                                        LA39=c85_age,
                                                                                        LA40=c85_oposite,
                                                                                        LA41=c85_material,
                                                                                        LA42=c85_explain_past,
                                                                                        LA43=NA,
                                                                                        LA44=NA,
                                                                                        LA45=NA,
                                                                                        LA46=NA,
                                                                                        LA47=NA,
                                                                                        LA48=NA,
                                                                                        LA49=NA,
                                                                                        LA50=NA,
                                                                                        LA51=NA,
                                                                                        LA52=NA,
                                                                                        LA53=NA,
                                                                                        LA54=NA,
                                                                                        LA55=NA,
                                                                                        LA56=NA,
                                                                                        LA57=NA,
                                                                                        LA58=NA,
                                                                                        SO1=c85_smile,
                                                                                        SO2=c85_smile_person,
                                                                                        SO3=c85_playful_with,
                                                                                        SO4=NA,
                                                                                        SO5=c85_playful,
                                                                                        SO6=c85_spoon_fed,
                                                                                        SO7=c85_hold_cup,
                                                                                        SO8=c85_strech,
                                                                                        SO9=c85_hold_spoon,
                                                                                        SO10=c85_point,
                                                                                        SO11=c85_pick_food,
                                                                                        SO12=NA,
                                                                                        SO13=c85_cup_drink,
                                                                                        SO14=c85_hand_up,
                                                                                        SO15=c85_spoon_no_spil,
                                                                                        SO16=c85_pick_food,
                                                                                        SO17=c85_asks_food,
                                                                                        SO18=c85_potty,
                                                                                        SO19=c85_greet,
                                                                                        SO20=c85_join_sing,
                                                                                        SO21=c85_undress,
                                                                                        SO22=NA,
                                                                                        SO23=c85_share,
                                                                                        SO24=c85_spoon_no_spil,
                                                                                        SO25=c85_eat_bit,
                                                                                        SO26=c85_chore,
                                                                                        SO27=c85_wash_hand,
                                                                                        SO28=c85_toilet,
                                                                                        SO29=NA,
                                                                                        SO30=c85_dress_part,
                                                                                        SO31=NA,
                                                                                        SO32=c85_dress,
                                                                                        SO33=c85_independence,
                                                                                        SO34=NA,
                                                                                        SO35=NA,
                                                                                        SO36=NA,
                                                                                        SO37=c85_take_turn,
                                                                                        SO38=c85_respect,
                                                                                        SO39=c85_discipline,
                                                                                        SO40=c85_toilet_self,
                                                                                        SO41=c85_quiet,
                                                                                        SO42=NA,
                                                                                        SO43=NA,
                                                                                        SO44=NA,
                                                                                        SO45=NA,
                                                                                        SO46=NA,
                                                                                        SO47=NA,
                                                                                        SO48=NA,
                                                                                        SO49=NA,
                                                                                        SO50=NA,
                                                                                        SO51=NA,
                                                                                        SO52=NA,
                                                                                        SO53=NA,
                                                                                        SO54=NA,
                                                                                        SO55=NA
                                                                                        
                                                                                        
  ) %>% mutate_all(., ~replace(.,  .=="98", NA))
) %>% write_csv("output/Data_template_NA_36m_48m_v1.1.csv")
#is.na(.) |


# cambiar los 98 y NA del inicio por 1
mdat_36_48<-dt_mdat<-read_csv("data/mdat/HAPINIIGuatemala-Revisionmdat_DATA_2023-05-12_1736.csv")
dt_mdat %>% mutate(
  id=as.character(record_id),
  visit=case_when(
    redcap_event_name=="24_month_arm_1" ~ "b5",
    redcap_event_name=="year_3_q1_36m_arm_1" ~ "b6",
    redcap_event_name=="year4_q1_48m_arm_1" ~ "b7"
  )
) %>% select(id,visit, everything(), -record_id, -redcap_event_name)

length(mdat_36_48)

#validar todos los NA o 98 por 1 en motor grueso
mdat_mg<-mdat_36_48 %>% select(
  #MG
  1,2,6:23
) %>%   mutate_all(., ~replace(., is.na(.) | .=="98", 1))

#validar todos los  98 por NA en motor grueso
mdat_mg2<-mdat_36_48 %>% select(
  #MG
  1,2,24:44
) %>%   mutate_all(., ~replace(., .=="98", NA))



#validar todos los NA o 98 por 1 en motor fino
mdat_mf<-mdat_36_48 %>% select(
  #MG
  1,2,45:66
) %>%   mutate_all(., ~replace(., is.na(.) | .=="98", 1)) 

#validar todos los  98 por NA en motor fino
mdat_mf2<-mdat_36_48 %>% select(
  #MG
  1,2,67:85
) %>%   mutate_all(., ~replace(., .=="98", NA))



#validar todos los NA o 98 por 1 en Lenguaje
mdat_l<-mdat_36_48 %>% select(
  #MG
  1,2,86:100
) %>%   mutate_all(., ~replace(., is.na(.) | .=="98", 1)) 

#validar todos los  98 por NA en Lenguaje
mdat_l2<-mdat_36_48 %>% select(
  #MG
  1,2,101:125
) %>%   mutate_all(., ~replace(.,  .=="98", NA)) 


#validar todos los NA o 98 por 1 en Social
mdat_s<-mdat_36_48 %>% select(
  #MG
  1,2,126:138
) %>%   mutate_all(., ~replace(., is.na(.) | .=="98", 1)) 

#validar todos los 98 por NA en Social
mdat_s2<-mdat_36_48 %>% select(
  #MG
  1,2,139:161
) %>%   mutate_all(., ~replace(., is.na(.) | .=="98", 1)) 

#integrar set de datos validados

dt_mdat_validado<-mdat_mg %>% left_join(
  mdat_mg2
) %>% left_join(
  mdat_mf
) %>% left_join(
  mdat_mf2
) %>% left_join(
  mdat_l
) %>% left_join(
  mdat_l2
) %>% left_join(
  mdat_s
) %>% left_join(
  mdat_s2
) %>% mutate(
  id=as.character(record_id),
  visit=case_when(
    redcap_event_name=="24_month_arm_1" ~ "b5",
    redcap_event_name=="year_3_q1_36m_arm_1" ~ "b6",
    redcap_event_name=="year4_q1_48m_arm_1" ~ "b7"
  )
) %>% select(id, visit, everything(),-record_id, -redcap_event_name)

#integrar csv para subir en shiny app
gt_hapin_II_data %>% filter(!is.na(c85_date))  %>% select(id, fecha_c85=c85_date) %>% 
  left_join(
    gt_emory_data_arm2 %>% filter(!is.na(c30_dob)) %>% select(id, fec_nac=c30_dob)
  ) %>% mutate(
    age=round((as.Date(fecha_c85) - as.Date(fec_nac))/365,2)
  ) %>% select(original_id=id, decimalage=age) %>% left_join(
  dt_mdat_validado %>% transmute(original_id=as.character(id),
                          GM1=c85_chin,
                          GM2=c85_prone,
                          GM3=c85_lift_head,
                          GM4=c85_headup,
                          GM5=c85_pullsit,
                          GM6=c85_sit,
                          GM7=NA,
                          GM8=c85_bear_wt,
                          GM9=c85_roll,
                          GM10=c85_sit_10sec,
                          GM11=c85_sit_30sec,
                          GM12=c85_crawl,
                          GM13=c85_pull_stand,
                          GM14=c85_hold_stand,
                          GM15=NA,
                          GM16=c85_walk_2hand,
                          GM17=c85_walk_help,
                          GM18=c85_walk_fall,
                          GM19=c85_stoop,
                          GM20=c85_walk_well,
                          GM21=NA,
                          GM22=c85_run,
                          GM23=c85_run_well,
                          GM24=c85_kick,
                          GM25=c85_run_kick,
                          GM26=c85_ball_basket,
                          GM27=c85_kneel_up,
                          GM28=NA,
                          GM29=c85_jump_off,
                          GM30=c85_jump_over,
                          GM31=c85_walk_heel,
                          GM32=c85_tip_toe,
                          GM33=c85_stand_1foot,
                          GM34=c85_1foot_5sec,
                          GM35=NA,
                          GM36=c85_jump_a4,
                          GM37=c85_hop,
                          GM38=NA,
                          GM39=c85_walk_string,
                          GM40=NA,
                          GM41=c85_catch_ball,
                          GM42=NA,
                          GM43=NA,
                          GM44=NA,
                          GM45=NA,
                          FM1=c85_follow_mom,
                          FM2=c85_follow_rl,
                          FM3=c85_hands_eye,
                          FM4=c85_reach_large,
                          FM5=c85_hold_large,
                          FM6=c85_object_mouth,
                          FM7=c85_look_small,
                          FM8=c85_pick_large,
                          FM9=c85_transfer,
                          FM10=c85_clap,
                          FM11=c85_pick_small,
                          FM12=c85_hidden,
                          FM13=c85_pincer,
                          FM14=c85_push_car,
                          FM15=NA,
                          FM16=c85_in_jar,
                          FM17=c85_out_jar,
                          FM18=c85_straight_line,
                          FM19=c85_circular_line,
                          FM20=NA,
                          FM21=NA,
                          FM22=NA,
                          FM23=c85_peg_2min,
                          FM24=c85_peg_30sec,
                          FM25.2=NA,
                          FM25.4=NA,
                          FM25.6=NA,
                          FM26=c85_screw,
                          FM27=NA,
                          FM28=c85_vertical,
                          FM29=c85_circle,
                          FM30=c85_cross,
                          FM31=c85_bridge,
                          FM32=c85_thread,
                          FM33=NA,
                          FM34=NA,
                          FM35=c85_size,
                          FM36=c85_weight,
                          FM37=c85_fold,
                          FM38=c85_square,
                          FM39=c85_6bridge,
                          FM40=c85_6stair,
                          FM41=c85_top_row,
                          FM42=c85_top_sq,
                          FM43=NA,
                          FM44=NA,
                          FM45=NA,
                          FM46=NA,
                          FM47=NA,
                          FM48=NA,
                          FM49=NA,
                          FM50=NA,
                          FM51=NA,
                          FM52=NA,
                          FM53=NA,
                          FM54=NA,
                          FM55=NA,
                          FM56=NA,
                          LA1=c85_startle,
                          LA2=c85_happy,
                          LA3=c85_laugh,
                          LA4=c85_turns,
                          LA5=c85_single_syl,
                          LA6=c85_two_syl,
                          LA7=c85_understand_no,
                          LA8=c85_resp_name,
                          LA9=c85_indicate_no,
                          LA10=c85_1command,
                          LA11=c85_pretend_talk,
                          LA12.2=c85_words,
                          LA12.4=NA,
                          LA12.6=c85_6words,
                          LA12.8=NA,
                          LA13=c85_words,
                          LA14.5=c85_5_identify,
                          LA14.10=c85_10_identify,
                          LA15=c85_2command,
                          LA16=NA,
                          LA17=NA,
                          LA18=c85_bodypart,
                          LA19=NA,
                          LA20.5=c85_5_name,
                          LA20.10=c85_10_name,
                          LA21=NA,
                          LA22=c85_sentence,
                          LA23=c85_actions,
                          LA24=c85_own_name,
                          LA25=NA,
                          LA26=c85_position,
                          LA27=NA,
                          LA28=c85_adjec,
                          LA29=c85_know_use,
                          LA30.2=c85_2repeat_syl,
                          LA30.4=c85_4repeat_syl,
                          LA31=c85_faster,
                          LA32=c85_categorize,
                          LA33=c85_3stage,
                          LA34=NA,
                          LA35.3=c85_3count,
                          LA35.5=c85_5count,
                          LA35.10=c85_10count,
                          LA36=NA,
                          LA37=c85_sing,
                          LA38=NA,
                          LA39=c85_age,
                          LA40=c85_oposite,
                          LA41=c85_material,
                          LA42=c85_explain_past,
                          LA43=NA,
                          LA44=NA,
                          LA45=NA,
                          LA46=NA,
                          LA47=NA,
                          LA48=NA,
                          LA49=NA,
                          LA50=NA,
                          LA51=NA,
                          LA52=NA,
                          LA53=NA,
                          LA54=NA,
                          LA55=NA,
                          LA56=NA,
                          LA57=NA,
                          LA58=NA,
                          SO1=c85_smile,
                          SO2=c85_smile_person,
                          SO3=c85_playful_with,
                          SO4=NA,
                          SO5=c85_playful,
                          SO6=c85_spoon_fed,
                          SO7=c85_hold_cup,
                          SO8=c85_strech,
                          SO9=c85_hold_spoon,
                          SO10=c85_point,
                          SO11=c85_pick_food,
                          SO12=NA,
                          SO13=c85_cup_drink,
                          SO14=c85_hand_up,
                          SO15=c85_spoon_no_spil,
                          SO16=c85_pick_food,
                          SO17=c85_asks_food,
                          SO18=c85_potty,
                          SO19=c85_greet,
                          SO20=c85_join_sing,
                          SO21=c85_undress,
                          SO22=NA,
                          SO23=c85_share,
                          SO24=c85_spoon_no_spil,
                          SO25=c85_eat_bit,
                          SO26=c85_chore,
                          SO27=c85_wash_hand,
                          SO28=c85_toilet,
                          SO29=NA,
                          SO30=c85_dress_part,
                          SO31=NA,
                          SO32=c85_dress,
                          SO33=c85_independence,
                          SO34=NA,
                          SO35=NA,
                          SO36=NA,
                          SO37=c85_take_turn,
                          SO38=c85_respect,
                          SO39=c85_discipline,
                          SO40=c85_toilet_self,
                          SO41=c85_quiet,
                          SO42=NA,
                          SO43=NA,
                          SO44=NA,
                          SO45=NA,
                          SO46=NA,
                          SO47=NA,
                          SO48=NA,
                          SO49=NA,
                          SO50=NA,
                          SO51=NA,
                          SO52=NA,
                          SO53=NA,
                          SO54=NA,
                          SO55=NA
                          
                          
)
) %>% write_csv("output/Data_template_validado_36m_48m_v1.1.csv")
