---
title: "Productividad hapin"
author: "AIR"
date: "18/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
# Emory RedCap export data
source(file = "scripts/0_get_emory_data.R", encoding = "UTF-8")

# Participant information (z10)
source(file = "scripts/0_get_participants.R", encoding = "UTF-8")

# Participant information (z10)
source(file = "scripts/0_get_salidas.R", encoding = "UTF-8")
# Participant information (z10)
source(file = "scripts/0_get_e3.R", encoding = "UTF-8")

# Emory HAPIN II  
source(file = "scripts/0_get_hapinII.R", encoding = "UTF-8")


library("tidyverse")
library(ggplot2)
library(cowplot) 
library("RColorBrewer")
library(kableExtra)


#______________________________________________________________________
#SACAR LISTA DE COMUNIDADES CON BASE EN CATALOGO DE COMUNIDADES JALAPA
#_____________________________________________________________________
#---------------------------------------------------------------------
comunidades<-gt_participants %>% select(record_id,id_estudio, com_jalapa, com_jalapa_new, lat, long) %>%
  mutate(house_id=if_else(condition = grepl("^G[0-9]{4}",id_estudio),
                          true = record_id,
                          false = id_estudio
  )) %>% mutate(
    id_tamizaje=if_else(
      condition = grepl("^G[0-9]{4}",record_id),
      true = record_id,
      false = id_estudio
    )) %>%  mutate(
      community = recode(
        com_jalapa,
        "2101308" = "SANTA CRUZ",
        "2101283" = "EL MILAGRO",
        "2101127" = "LAS JOYITAS",
        "2101045" = "LAS GALERAS",
        "2101207" = "LAS PEAS",
        "2101006" = "ANSHIGUA",
        "2101181" = "CARRIZALITO",
        "2101220" = "SHICAL",
        "2101200" = "LA PASTORIA",
        "2101115" = "POTRERO CARRILLO",
        "2101210" = "LOS PINOS",
        "2101131" = "SAN LORENZO",
        "2101076" = "LA PUENTE",
        "2101202" = "LA LAGUNA",
        "2101072" = "LOS LIMARES",
        "2101035" = "EL MOJON",
        "2101351" = "LAGUNA VERDE",
        "2101173" = "SAN LUIS GUISHORO",
        "2101138" = "SANTA ELENA",
        "2101216" = "RIO FRIO",
        "2101132" = "SAN ANTONIO LA NORIA",
        "2101182" = "EL CASCABILLAL Y EL COPALITO",
        "2101080" = "LOS CIEGOS",
        "2101137" = "SAN IGNACIO",
        "2101151" = "LA VENTURA",
        "2101104" = "LLANO DE LA PUERTA",
        "2101175" = "LOS MEZCALES",
        "2101020" = "CHAGUITE",
        "2101116" = "POTRERO DEL BURRO",
        "2101014" = "EL CARRIZAL",
        "2101129" = "SAN JOSE",
        "2101030" = "EL TALQUEZAL",
        "2101032" = "EL RODEO",
        "2101145" = "TIERRA BLANCA",
        "2101081" = "LAGUNETA LOS ACHIOTES O QUEBRADA HONDA",
        "2101002" = "ACHIOTES JUMAY",
        "2101238" = "EL GUAJE",
        "2101070" = "LOS TALPETATES",
        "2101036" = "EL TABLON",
        "2101083" = "LA TEJERA",
        "2101074" = "LOS IZOTES",
        "2101123" = "SANSAYO",
        "2101113" = "PATA GALANA",
        "2101114" = "PALO VERDE",
        "2101039" = "EL LIMON",
        "2101241" = "EL PINALITO",
        "2101251" = "LA LAGUNILLA",
        "2101134" = "SANSURUTATE",
        "2101037" = "EL TERRERO I",
        "2101157" = "YERBABUENA",
        "2101203" = "LAGUNETA EL SAPO",
        "2101195" = "ITZACOBA",
        "2101227" = "VOLCAN PAZ",
        "2101071" = "LA PAZ",
        "2101124" = "SASHICO",
        "2101022" = "EL DURAZNAL",
        "2101133" = "SUQUINAY",
        "2101021" = "DIVISADERO",
        "2101128" = "SANYUYO",
        "2101150" = "VOLCAN SANYUYO",
        "2101253" = "LAS MARIAS",
        "2101027" = "EL PITO",
        "2101208" = "LAS PIEDRAS",
        "2101015" = "CERRO DE ALCOBA",
        "2101060" = "LAZARETO",
        "2101172" = "LOS GONZALEZ",
        "2101052" = "LA FUENTE DE LA MONTAA",
        "2101029" = "EL DURAZNO",
        "2101117" = "PINO GORDO",
        "2101031" = "EL ROBLAR",
        "2101028" = "EL ARENAL",
        "2101062" = "LA AURORA",
        "2101068" = "LA LAGUNETA",
        "2101166" = "AGUA ZARCA",
        "2101026" = "EL DURAZNITO",
        "2101265" = "LAS CRUCES",
        "2101125" = "SAN JOSE LA FUENTE",
        "2101023" = "EL PARAISO",
        "2101147" = "URLANTA",
        "2101010" = "EL MIRADOR",
        "2101188" = "EL COYOTE",
        "2101224" = "TRUJILLO",
        "2101065" = "LOS LLANITOS",
        "2101007" = "ARLOROMA",
        "2101148" = "URAYANSAPO",
        "2101179" = "ARAISAPO",
        "2101144" = "TATASIRIRE",
        "2101066" = "LAS AZUCENAS",
        "2101193" = "GOLFILLO",
        "2101061" = "LOS TABLONES",
        "2101012" = "BUENA VISTA",
        "2101064" = "LOMA DE ENMEDIO",
        "2101105" = "MIRAFLORES",
        "2101053" = "LAS GUACAMAYAS",
        "2101205" = "LAS JOYAS",
        "2101004" = "ALTUPE",
        "2101009" = "EL AGUACATE",
        "2101025" = "EL BOSQUE",
        "2101016" = "CORONA",
        "2101213" = "LA PIEDRONA",
        "2101099" = "LOS CEDROS",
        "2101222" = "SUQUINAY",
        "2101109" = "MOJON DEL MUERTO",
        "2101106" = "MIRAMUNDO",
        "2101108" = "MAL PASO",
        "2101232" = "SAUSAL",
        "2101187" = "EL CONFITERO",
        "2101102" = "LAS MORITAS",
        "2101110" = "ORCHOJ",
        "2101011" = "AGUIJOTES",
        "2101120" = "QUEBRADITAS",
        "2101196" = "JOYA GRANDE",
        "2101250" = "LOS LOPEZ",
        "2101249" = "EL ASTILLERO",
        "2101247" = "SHICAL",
        "2101159" = "CARTAGO",
        "2101121" = "RIO BLANCO",
        "2101047" = "EL RODEO",
        "2101059" = "JICALTEPEQUE",
        "2101003" = "ASTILLERO",
        "2101215" = "RIO BLANCO ARRIBA",
        "2101201" = "LA VICENTINA",
        "2101158" = "LAS TAPIAS",
        "2101255" = "LAGUNA VERDE",
        "2101252" = "GARCIA",
        "2101063" = "LAS DELICIAS",
        "2101161" = "VAREJONES",
        "2101051" = "EL ZAPOTE",
        "2101044" = "EL RETIRO",
        "2101997" = "POBLACION DISPERSA",
        "2101310" = "SAN LORENZO",
        "2101041" = "EL TIGRE",
        "2101311" = "SAN FRANSISICO BELLA VISTA",
        "2101312" = "LA ESMERALDA",
        "2101352" = "LINDA VISTA",
        "2101314" = "INGENIO DE LOS FIERROS",
        "2101315" = "CARTAGO",
        "2101180" = "BETHANIA",
        "2101362" = "VILLA ADRIANA",
        "2101355" = "SALFATE",
        "2101316" = "LAS LOMITAS",
        "2101257" = "CARRIZALITO",
        "2101318" = "PARINAQUE",
        "2101354" = "EL CAFETAL",
        "2101103" = "LLANO GRANDE",
        "2101319" = "MOSQUITO",
        "2101320" = "HATO VIEJO",
        "2101321" = "INGENIO DE AYARZA",
        "2101361" = "VERDUGO",
        "2101322" = "CUESTA GRANDE",
        "2101323" = "EL JUTE",
        "2101324" = "GRACIAS A DIOS",
        "2101325" = "EL SAUZAL",
        "2101326" = "LA TOMA",
        "2101327" = "EL VOLCAN",
        "2101328" = "LA LAGUNA",
        "2101329" = "LA CUCHILLA",
        "2101330" = "TALQUETZAL",
        "2101126" = "SANSIRISAY",
        "2101331" = "LA TEJERA",
        "2101332" = "SAN FRANCISCO",
        "2101333" = "SANCASTI",
        "2101334" = "AGUA CALIENTE",
        "2101335" = "EL SITIO",
        "2101336" = "CEBOLLIN",
        "2101337" = "EL AGUACATE",
        "2101338" = "LOS LLANITOS",
        "2101339" = "RASTROJO LIMPIO",
        "2101359" = "EL CEDRO",
        "2101340" = "EL INCIENSO",
        "2101341" = "AGUA BLANCA",
        "2101342" = "LAGUNA",
        "2101343" = "LAS MARIAS",
        "2101344" = "LA CARBONERA",
        "2101346" = "LA VENTANA",
        "2101350" = "LAS CRUCESITAS",
        "2101270" = "SAN FERNANDO O CAMELOT",
        "2101090" = "LAGUNA VERDE",
        "2101254" = "JOSE LA CARBONERA",
        "2101347" = "LAGUNA VERDE",
        "2101235" = "AGUA BLANCA",
        "2101017" = "DOBLE R",
        "2101034" = "HACIENDA LA PONDEROSA",
        "2101139" = "SAN MIGUEL",
        "2101256" = "LA CIENEGA",
        "2101018" = "SAN ISIDRO",
        "2101240" = "EL CARMEN",
        "2101309" = "EL CARMEN",
        "2101268" = "EL CHAGUITE",
        "2101239" = "LAS UVAS",
        "2101033" = "EL MANGUITO",
        "2101348" = "LOS MEZCALES",
        "2101358" = "EL AGUACATE",
        "2101111" = "OJO DE AGUA",
        "2101194" = "INGENIO FIERRO",
        "2101357" = "SABANETAS",
        "2101360" = "COCALES",
        "2101048" = "EL JUTILLO",
        "2101293" = "ESTACON",
        "2101353" = "LA BOTIJA",
        "2101349" = "SAN FRANSISCO POZA VERDE",
        "2101001" = "JALAPA",
        "999" = "OTRA"
      ),
      community_new = recode(
        com_jalapa_new,
        "2101308" = "SANTA CRUZ",
        "2101283" = "EL MILAGRO",
        "2101127" = "LAS JOYITAS",
        "2101045" = "LAS GALERAS",
        "2101207" = "LAS PEAS",
        "2101006" = "ANSHIGUA",
        "2101181" = "CARRIZALITO",
        "2101220" = "SHICAL",
        "2101200" = "LA PASTORIA",
        "2101115" = "POTRERO CARRILLO",
        "2101210" = "LOS PINOS",
        "2101131" = "SAN LORENZO",
        "2101076" = "LA PUENTE",
        "2101202" = "LA LAGUNA",
        "2101072" = "LOS LIMARES",
        "2101035" = "EL MOJON",
        "2101351" = "LAGUNA VERDE",
        "2101173" = "SAN LUIS GUISHORO",
        "2101138" = "SANTA ELENA",
        "2101216" = "RIO FRIO",
        "2101132" = "SAN ANTONIO LA NORIA",
        "2101182" = "EL CASCABILLAL Y EL COPALITO",
        "2101080" = "LOS CIEGOS",
        "2101137" = "SAN IGNACIO",
        "2101151" = "LA VENTURA",
        "2101104" = "LLANO DE LA PUERTA",
        "2101175" = "LOS MEZCALES",
        "2101020" = "CHAGUITE",
        "2101116" = "POTRERO DEL BURRO",
        "2101014" = "EL CARRIZAL",
        "2101129" = "SAN JOSE",
        "2101030" = "EL TALQUEZAL",
        "2101032" = "EL RODEO",
        "2101145" = "TIERRA BLANCA",
        "2101081" = "LAGUNETA LOS ACHIOTES O QUEBRADA HONDA",
        "2101002" = "ACHIOTES JUMAY",
        "2101238" = "EL GUAJE",
        "2101070" = "LOS TALPETATES",
        "2101036" = "EL TABLON",
        "2101083" = "LA TEJERA",
        "2101074" = "LOS IZOTES",
        "2101123" = "SANSAYO",
        "2101113" = "PATA GALANA",
        "2101114" = "PALO VERDE",
        "2101039" = "EL LIMON",
        "2101241" = "EL PINALITO",
        "2101251" = "LA LAGUNILLA",
        "2101134" = "SANSURUTATE",
        "2101037" = "EL TERRERO I",
        "2101157" = "YERBABUENA",
        "2101203" = "LAGUNETA EL SAPO",
        "2101195" = "ITZACOBA",
        "2101227" = "VOLCAN PAZ",
        "2101071" = "LA PAZ",
        "2101124" = "SASHICO",
        "2101022" = "EL DURAZNAL",
        "2101133" = "SUQUINAY",
        "2101021" = "DIVISADERO",
        "2101128" = "SANYUYO",
        "2101150" = "VOLCAN SANYUYO",
        "2101253" = "LAS MARIAS",
        "2101027" = "EL PITO",
        "2101208" = "LAS PIEDRAS",
        "2101015" = "CERRO DE ALCOBA",
        "2101060" = "LAZARETO",
        "2101172" = "LOS GONZALEZ",
        "2101052" = "LA FUENTE DE LA MONTAA",
        "2101029" = "EL DURAZNO",
        "2101117" = "PINO GORDO",
        "2101031" = "EL ROBLAR",
        "2101028" = "EL ARENAL",
        "2101062" = "LA AURORA",
        "2101068" = "LA LAGUNETA",
        "2101166" = "AGUA ZARCA",
        "2101026" = "EL DURAZNITO",
        "2101265" = "LAS CRUCES",
        "2101125" = "SAN JOSE LA FUENTE",
        "2101023" = "EL PARAISO",
        "2101147" = "URLANTA",
        "2101010" = "EL MIRADOR",
        "2101188" = "EL COYOTE",
        "2101224" = "TRUJILLO",
        "2101065" = "LOS LLANITOS",
        "2101007" = "ARLOROMA",
        "2101148" = "URAYANSAPO",
        "2101179" = "ARAISAPO",
        "2101144" = "TATASIRIRE",
        "2101066" = "LAS AZUCENAS",
        "2101193" = "GOLFILLO",
        "2101061" = "LOS TABLONES",
        "2101012" = "BUENA VISTA",
        "2101064" = "LOMA DE ENMEDIO",
        "2101105" = "MIRAFLORES",
        "2101053" = "LAS GUACAMAYAS",
        "2101205" = "LAS JOYAS",
        "2101004" = "ALTUPE",
        "2101009" = "EL AGUACATE",
        "2101025" = "EL BOSQUE",
        "2101016" = "CORONA",
        "2101213" = "LA PIEDRONA",
        "2101099" = "LOS CEDROS",
        "2101222" = "SUQUINAY",
        "2101109" = "MOJON DEL MUERTO",
        "2101106" = "MIRAMUNDO",
        "2101108" = "MAL PASO",
        "2101232" = "SAUSAL",
        "2101187" = "EL CONFITERO",
        "2101102" = "LAS MORITAS",
        "2101110" = "ORCHOJ",
        "2101011" = "AGUIJOTES",
        "2101120" = "QUEBRADITAS",
        "2101196" = "JOYA GRANDE",
        "2101250" = "LOS LOPEZ",
        "2101249" = "EL ASTILLERO",
        "2101247" = "SHICAL",
        "2101159" = "CARTAGO",
        "2101121" = "RIO BLANCO",
        "2101047" = "EL RODEO",
        "2101059" = "JICALTEPEQUE",
        "2101003" = "ASTILLERO",
        "2101215" = "RIO BLANCO ARRIBA",
        "2101201" = "LA VICENTINA",
        "2101158" = "LAS TAPIAS",
        "2101255" = "LAGUNA VERDE",
        "2101252" = "GARCIA",
        "2101063" = "LAS DELICIAS",
        "2101161" = "VAREJONES",
        "2101051" = "EL ZAPOTE",
        "2101044" = "EL RETIRO",
        "2101997" = "POBLACION DISPERSA",
        "2101310" = "SAN LORENZO",
        "2101041" = "EL TIGRE",
        "2101311" = "SAN FRANSISICO BELLA VISTA",
        "2101312" = "LA ESMERALDA",
        "2101352" = "LINDA VISTA",
        "2101314" = "INGENIO DE LOS FIERROS",
        "2101315" = "CARTAGO",
        "2101180" = "BETHANIA",
        "2101362" = "VILLA ADRIANA",
        "2101355" = "SALFATE",
        "2101316" = "LAS LOMITAS",
        "2101257" = "CARRIZALITO",
        "2101318" = "PARINAQUE",
        "2101354" = "EL CAFETAL",
        "2101103" = "LLANO GRANDE",
        "2101319" = "MOSQUITO",
        "2101320" = "HATO VIEJO",
        "2101321" = "INGENIO DE AYARZA",
        "2101361" = "VERDUGO",
        "2101322" = "CUESTA GRANDE",
        "2101323" = "EL JUTE",
        "2101324" = "GRACIAS A DIOS",
        "2101325" = "EL SAUZAL",
        "2101326" = "LA TOMA",
        "2101327" = "EL VOLCAN",
        "2101328" = "LA LAGUNA",
        "2101329" = "LA CUCHILLA",
        "2101330" = "TALQUETZAL",
        "2101126" = "SANSIRISAY",
        "2101331" = "LA TEJERA",
        "2101332" = "SAN FRANCISCO",
        "2101333" = "SANCASTI",
        "2101334" = "AGUA CALIENTE",
        "2101335" = "EL SITIO",
        "2101336" = "CEBOLLIN",
        "2101337" = "EL AGUACATE",
        "2101338" = "LOS LLANITOS",
        "2101339" = "RASTROJO LIMPIO",
        "2101359" = "EL CEDRO",
        "2101340" = "EL INCIENSO",
        "2101341" = "AGUA BLANCA",
        "2101342" = "LAGUNA",
        "2101343" = "LAS MARIAS",
        "2101344" = "LA CARBONERA",
        "2101346" = "LA VENTANA",
        "2101350" = "LAS CRUCESITAS",
        "2101270" = "SAN FERNANDO O CAMELOT",
        "2101090" = "LAGUNA VERDE",
        "2101254" = "JOSE LA CARBONERA",
        "2101347" = "LAGUNA VERDE",
        "2101235" = "AGUA BLANCA",
        "2101017" = "DOBLE R",
        "2101034" = "HACIENDA LA PONDEROSA",
        "2101139" = "SAN MIGUEL",
        "2101256" = "LA CIENEGA",
        "2101018" = "SAN ISIDRO",
        "2101240" = "EL CARMEN",
        "2101309" = "EL CARMEN",
        "2101268" = "EL CHAGUITE",
        "2101239" = "LAS UVAS",
        "2101033" = "EL MANGUITO",
        "2101348" = "LOS MEZCALES",
        "2101358" = "EL AGUACATE",
        "2101111" = "OJO DE AGUA",
        "2101194" = "INGENIO FIERRO",
        "2101357" = "SABANETAS",
        "2101360" = "COCALES",
        "2101048" = "EL JUTILLO",
        "2101293" = "ESTACON",
        "2101353" = "LA BOTIJA",
        "2101349" = "SAN FRANSISCO POZA VERDE",
        "2101001" = "JALAPA",
        "999" = "OTRA"
      )
    )



#------------------------------------------------
#VISITAS C31
#-----------------
#catalogo de rutas
rutas<-read_csv("data/cat_rutas_visitas.csv")
#fecha1="2022-05-15"
fecha2="2022-11-08"

```



```{r}

#para equipo de reclutamiento tomar M10
rec_semana<-gt_hapin_II_data %>% filter(!is.na(m10_date)) %>% filter(visit=="b6") %>% select(
  m10_date, m10_by
) %>% mutate(
  semana=lubridate::week(m10_date),
  mes=lubridate::month(m10_date),
  Mes=format(m10_date, "%B")
) %>% arrange(semana) %>% group_by(semana) %>% count() %>% mutate(media=round(n/5)) %>% select(-n) %>% 
  mutate(equipo="Reclutamiento")

rec_mes<-gt_hapin_II_data %>% filter(!is.na(m10_date)) %>% filter(visit=="b6") %>% select(
  m10_date, m10_by
) %>% mutate(
  semana=lubridate::week(m10_date),
  mes=lubridate::month(m10_date),
  Mes=format(m10_date, "%B")
) %>% arrange(semana) %>% group_by(mes,Mes) %>% count() %>% mutate(media=round(n/20)) %>% select(-n) %>% 
  mutate(equipo="Reclutamiento")

#para equipo de reclutamiento tomar H41
exp_semana<-gt_hapin_II_data %>% filter(!is.na(h41_date_v2)) %>% filter(visit=="b6") %>% select(
  h41_date_v2, h41_by_v2
) %>% mutate(
  semana=lubridate::week(h41_date_v2),
  mes=lubridate::month(h41_date_v2),
  Mes=format(h41_date_v2, "%B")
) %>% arrange(semana) %>% group_by(semana) %>% count() %>% mutate(media=round(n/5)) %>% select(-n) %>% 
  mutate(equipo="Exposicion")

exp_mes<-gt_hapin_II_data %>% filter(!is.na(h41_date_v2)) %>% filter(visit=="b6") %>% select(
  h41_date_v2, h41_by_v2
) %>% mutate(
  semana=lubridate::week(h41_date_v2),
  mes=lubridate::month(h41_date_v2),
  Mes=format(h41_date_v2, "%B")
) %>% arrange(mes,Mes) %>% group_by(mes,Mes) %>% count() %>% mutate(media=round(n/20)) %>% select(-n) %>% 
  mutate(equipo="Exposicion")

#integramos medias de equipos
g_equipo_semana<- rec_semana %>% bind_rows(
  exp_semana
) %>% ggplot(
 aes(x=semana, y=media, color=equipo)
)+ geom_line(stat="identity", size=1)+ 
  #geom_bar(stat = "identity", position = "dodge") + 
  theme(axis.text.x = element_text( size = 8))+
   scale_x_continuous(name="Semana", breaks = c(8:52)) + scale_y_continuous(name="Media", breaks = c(0:12))+
  labs(
    title = "MEDIA DE PRODUCTIVIDAD POR SEMANA",
    subtitle = "Hapin 36 meses",
    caption = "Indicador trazador Reclutamiento: M10, Exposicion: H41. Media estimada por 5 dias habiles"
  )  + theme(plot.title = element_text(hjust=0.5),
            plot.subtitle = element_text(hjust = 0.5),
            plot.caption = element_text(hjust=0.5, size = 7)
            ) 




g_equipo_mes<- rec_mes %>% bind_rows(
  exp_mes 
) %>%  ggplot(
 aes(x=mes, y=media, color=equipo)
)+ geom_line(stat="identity", size=1)+ 
  #geom_bar(stat = "identity", position = "dodge") + 
  theme(axis.text.x = element_text( size = 8))+
   scale_x_continuous(name="Mes", breaks = c(1:12)) + scale_y_continuous(name="Media", 
                                                                         breaks = c(0:12))+
  labs(
    title = "MEDIA DE PRODUCTIVIDAD POR MES",
    subtitle = "Hapin 36 meses",
    caption = "Indicador trazador Reclutamiento: M10, Exposicion: H41. Media estimada por 20 dias habiles"
  )  + theme(plot.title = element_text(hjust=0.5),
            plot.subtitle = element_text(hjust = 0.5),
            plot.caption = element_text(hjust=0.5, size = 6)
            ) 

#data grafica por iniciales reclutamiento
# rec_iniciales<-gt_hapin_II_data %>% filter(!is.na(m10_date)) %>% filter(visit=="b6") %>% select(
#   m10_date, iniciales=m10_by
# ) %>% mutate(
#   semana=lubridate::week(m10_date),
#   mes=lubridate::month(m10_date),
#   Mes=format(m10_date, "%B")
# ) %>% arrange(semana) %>% group_by(semana, iniciales) %>% count() %>% mutate(media=round(n/5)) %>% select(-n) %>% 
#   mutate(equipo="Reclutamiento")
# 
# rec_iniciales %>% group_by(iniciales) %>% count()
# gt_hapin_II_data %>% filter(m10_by=="1") %>% select(id, m10_by)
# 
# m10<-gt_hapin_II_data %>% filter(!is.na(m10_date)) %>% filter(visit=="b6") %>% select(
#   fecha=m10_date, iniciales=m10_by
# ) %>% mutate(
#   crf="m10",
#   semana=lubridate::week(fecha),
#   mes=lubridate::month(fecha),
#   Mes=format(fecha, "%B")
# ) %>% arrange(semana)
# 
# c31<-gt_hapin_II_data %>% filter(!is.na(c31_date_2)) %>% filter(visit=="b6") %>% select(
#   fecha=c31_date_2, iniciales=c31_by_2
# ) %>% mutate(
#   crf="c31",
#   semana=lubridate::week(fecha),
#   mes=lubridate::month(fecha),
#   Mes=format(fecha, "%B")
# ) %>% arrange(semana)
# 
# m10 %>% bind_rows(
#   c31
# ) %>% group_by(iniciales, crf, semana) %>% count()

#grafica por semana
g_equipo_semana

#tabla por semana

rec_semana %>% bind_rows(
  exp_semana
) %>% mutate(
  media_reclutamiento=if_else(equipo=="Reclutamiento",media, NA_real_),
  media_exposicion=if_else(equipo=="Exposicion",media, NA_real_),
) %>% filter(!is.na(media_reclutamiento)) %>% select(semana, media_reclutamiento) %>% 
  left_join(
    rec_semana %>% bind_rows(
  exp_semana
) %>% mutate(
  media_reclutamiento=if_else(equipo=="Reclutamiento",media, NA_real_),
  media_exposicion=if_else(equipo=="Exposicion",media, NA_real_),
) %>% filter(!is.na(media_exposicion)) %>% select(semana, media_exposicion)
    
  ) %>% kable(caption = paste0( "<center>REPORTE PRODUCTIVIDAD POR SEMANA<br>
                  HAPIN 36 meses al ", fecha2," </center>"), 
        align = "l") %>% 
    kable_classic(full_width=F, html_font = "Cambria") %>% column_spec(1, width = "2cm",  bold = T) %>%  kable_styling("striped", full_width = F) %>% scroll_box(width = "500px", height = "300px")

#grafica por mes
g_equipo_mes

#tabla mes
rec_mes %>% bind_rows(
  exp_mes
) %>% mutate(
  media_reclutamiento=if_else(equipo=="Reclutamiento",media, NA_real_),
  media_exposicion=if_else(equipo=="Exposicion",media, NA_real_),
) %>% filter(!is.na(media_reclutamiento)) %>% select(mes, Mes, media_reclutamiento) %>% 
  left_join(
    rec_mes %>% bind_rows(
  exp_mes
) %>% mutate(
  media_reclutamiento=if_else(equipo=="Reclutamiento",media, NA_real_),
  media_exposicion=if_else(equipo=="Exposicion",media, NA_real_),
) %>% filter(!is.na(media_exposicion)) %>% select(mes,Mes, media_exposicion)
    
  ) %>% ungroup() %>% arrange(mes) %>% select(-mes) %>%  kable(caption = paste0( "<center>REPORTE PRODUCTIVIDAD POR MES<br>
                  HAPIN 36 meses al ", fecha2," </center>"), 
        align = "l") %>% 
    kable_classic(full_width=F, html_font = "Cambria") %>% column_spec(1, width = "2cm",  bold = T) %>%  kable_styling("striped", full_width = F) %>% scroll_box(width = "500px", height = "300px")


```

```{r}
gt_hapin_II_data %>% filter(!is.na(s4_date)) %>% filter(visit=="b6") %>% transmute(
  fecha=s4_date, iniciales=s4_by, crf="s4"
) %>% bind_rows(
  gt_hapin_II_data %>% filter(!is.na(m10_date)) %>% filter(visit=="b6") %>% transmute(
  fecha=m10_date, iniciales=m10_by, crf="m10"
) 
)%>% 
  group_by(iniciales, crf) %>% count() %>% ggplot(
    aes(x=iniciales, y=n, fill=crf)
  ) + geom_bar(stat = "identity", position = "dodge")+labs(
                  title= "CRFS C36 REALIZADOS",
                  subtitle = " POR ENCUESTADOR"
                )

```

